using System;
using System.Text;

namespace Autonovel.Core.Prompts
{
    public static class FoundationPrompts
    {
        public const string WorldSystemPrompt = "You are a fantasy worldbuilder with deep knowledge of Sanderson's Laws, Le Guin's prose philosophy, and TTRPG-quality lore design. You write world bibles that are specific, interconnected, and imply depth beyond what's stated. You never use AI slop words (delve, tapestry, myriad, etc). You write in clean, direct prose. Every rule has a cost. Every cultural detail implies a history. Every location has a sensory signature.";

        public const string CharacterSystemPrompt = "You are a character designer for literary fiction with deep knowledge of wound/want/need/lie frameworks, Sanderson's three sliders, and dialogue distinctiveness. You create characters who feel like real people with contradictions, secrets, and speech patterns you can hear. You never use AI slop words. You write in clean, direct prose.";

        public const string OutlineSystemPrompt = "You are a novel architect with deep knowledge of Save the Cat beats, Sanderson's plotting principles, Dan Harmon's Story Circle, and MICE Quotient. You build outlines that an author can draft from without inventing structure on the fly. Every chapter has beats, emotional arc, and try-fail cycle type. You never use AI slop words. You write in clean, direct prose.";

        public static string BuildWorldPrompt(string seed, string voicePart2, string craft)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Build a complete world bible for this fantasy novel. This is the WORLD.MD file -- the definitive reference for everything that EXISTS in this world. A writer should be able to resolve any worldbuilding question from this document alone.");
            sb.AppendLine();
            sb.AppendLine("SEED CONCEPT:");
            sb.AppendLine(seed);
            sb.AppendLine();
            sb.AppendLine("VOICE IDENTITY (the tone and register of this novel):");
            sb.AppendLine(voicePart2);
            sb.AppendLine();
            sb.AppendLine("CRAFT REQUIREMENTS (from CRAFT.md -- follow these):");
            sb.AppendLine("- Magic system needs HARD RULES with COSTS and LIMITATIONS per Sanderson's Second Law");
            sb.AppendLine("- Limitations >= powers in narrative prominence");
            sb.AppendLine("- Trace implications of magic through society, economy, law, religion");
            sb.AppendLine("- At least 2-3 societal implications of magic explored in depth");
            sb.AppendLine("- History must create PRESENT-DAY TENSIONS that drive the plot (not just backdrop)");
            sb.AppendLine("- Geography must be specific and sensory (not generic fantasy)");
            sb.AppendLine("- Iceberg principle: imply more than you state");
            sb.AppendLine("- Interconnection: pulling one thread should move everything");
            sb.AppendLine();
            sb.AppendLine("STRUCTURE THE DOCUMENT WITH THESE SECTIONS:");
            sb.AppendLine();
            sb.AppendLine("## Cosmology & History");
            sb.AppendLine("A timeline of major events. Focus on events that create PRESENT-DAY tensions.");
            sb.AppendLine("Include the founding myth, key turning points, and recent events that matter to the plot.");
            sb.AppendLine();
            sb.AppendLine("## Magic System");
            sb.AppendLine("### Hard Rules (Tonal Law)");
            sb.AppendLine("Specific, testable rules. What intervals do what. What progressions bind.");
            sb.AppendLine("What happens when you break the rules. Include COSTS and LIMITATIONS prominently.");
            sb.AppendLine();
            sb.AppendLine("### Soft Magic (Cass's Gift)");
            sb.AppendLine("What he perceives, how it works, what it costs HIM specifically.");
            sb.AppendLine("This should be mysterious but have consistent internal logic.");
            sb.AppendLine();
            sb.AppendLine("### Societal Implications");
            sb.AppendLine("How does tonal law shape: governance, commerce, education, class structure,");
            sb.AppendLine("crime, family life, childhood, aging, disability?");
            sb.AppendLine();
            sb.AppendLine("## Geography");
            sb.AppendLine("Cantamura's physical layout, districts, the natural amphitheater's acoustic properties.");
            sb.AppendLine("Neighboring places (at least 2-3). Sensory signatures for each location.");
            sb.AppendLine();
            sb.AppendLine("## Factions & Politics");
            sb.AppendLine("Who holds power, who wants it, who's being crushed by it.");
            sb.AppendLine("At least 3-4 factions with opposing interests.");
            sb.AppendLine();
            sb.AppendLine("## Bestiary / Flora / Natural World");
            sb.AppendLine("What's unique about the natural world in and around Cantamura?");
            sb.AppendLine();
            sb.AppendLine("## Cultural Details");
            sb.AppendLine("Customs, taboos, festivals, food, clothing, coming-of-age rituals.");
            sb.AppendLine("Things that make daily life feel SPECIFIC.");
            sb.AppendLine();
            sb.AppendLine("## Internal Consistency Rules");
            sb.AppendLine("Hard constraints a writer must not violate. The physics of sound in this world.");
            sb.AppendLine("What's possible and what's not.");
            sb.AppendLine();
            sb.AppendLine("IMPORTANT:");
            sb.AppendLine("- Be SPECIFIC. Not \"the city has districts\" but name them, describe them, give them sensory signatures.");
            sb.AppendLine("- Every rule should have a COST or LIMITATION stated alongside it.");
            sb.AppendLine("- Include 2-3 facts per section that are unexplained, hinting at deeper systems (iceberg depth).");
            sb.AppendLine("- Facts should INTERCONNECT: the magic should shape the politics, the geography should shape the culture, the history should explain current faction conflicts.");
            sb.AppendLine("- Write in clean, direct prose. No AI slop. No \"rich tapestry.\" No \"delving.\"");
            sb.AppendLine("- The world should feel grounded and LIVED-IN, not imagined. Think: what does breakfast smell like? What do children play? How do old people complain?");
            sb.AppendLine("- Target ~3000-4000 words. Dense, not padded.");
            return sb.ToString();
        }

        public static string BuildCharacterPrompt(string seed, string world, string voicePart2)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Build a complete character registry for this fantasy novel. This is CHARACTERS.MD -- the definitive reference for WHO exists in this story, what drives them, how they speak, and what secrets they carry.");
            sb.AppendLine();
            sb.AppendLine("SEED CONCEPT:");
            sb.AppendLine(seed);
            sb.AppendLine();
            sb.AppendLine("WORLD BIBLE (the world these characters inhabit):");
            sb.AppendLine(world);
            sb.AppendLine();
            sb.AppendLine("VOICE IDENTITY (the novel's tone):");
            sb.AppendLine(voicePart2);
            sb.AppendLine();
            sb.AppendLine("CHARACTER CRAFT REQUIREMENTS (from CRAFT.md):");
            sb.AppendLine();
            sb.AppendLine("### The Three Sliders (Sanderson)");
            sb.AppendLine("Every character has three independent dials (0-10):");
            sb.AppendLine("  PROACTIVITY -- Do they drive the plot or react to it?");
            sb.AppendLine("  LIKABILITY  -- Does the reader empathize with them?");
            sb.AppendLine("  COMPETENCE  -- Are they good at what they do?");
            sb.AppendLine("Rule: compelling = HIGH on at least TWO, or HIGH on one with clear growth.");
            sb.AppendLine();
            sb.AppendLine("### Wound / Want / Need / Lie Framework");
            sb.AppendLine("A causal chain:");
            sb.AppendLine("  GHOST (backstory event) -> WOUND (ongoing damage) -> LIE (false belief to cope)");
            sb.AppendLine("    -> WANT (external goal driven by Lie) -> NEED (internal truth, opposes Lie)");
            sb.AppendLine("Rules: Want and Need must be IN TENSION. Lie statable in one sentence.");
            sb.AppendLine("  Truth is its direct opposite.");
            sb.AppendLine();
            sb.AppendLine("### Dialogue Distinctiveness (8 dimensions)");
            sb.AppendLine("1. Vocabulary level  2. Sentence length  3. Contractions/formality");
            sb.AppendLine("4. Verbal tics  5. Question vs statement ratio  6. Interruption patterns");
            sb.AppendLine("7. Metaphor domain  8. Directness vs indirectness");
            sb.AppendLine("Test: Remove dialogue tags. Can you tell who's speaking?");
            sb.AppendLine();
            sb.AppendLine("BUILD THE REGISTRY WITH AT LEAST THESE CHARACTERS:");
            sb.AppendLine();
            sb.AppendLine("1. **Cass Bellwright** (protagonist, POV character)");
            sb.AppendLine("   - Full wound/want/need/lie chain");
            sb.AppendLine("   - Three sliders with justification");
            sb.AppendLine("   - Arc type (positive/negative/flat)");
            sb.AppendLine("   - Detailed speech pattern (8 dimensions)");
            sb.AppendLine("   - Physical habits and tells");
            sb.AppendLine("   - At least 2 secrets");
            sb.AppendLine("   - Key relationships mapped");
            sb.AppendLine();
            sb.AppendLine("2. **Eddan Bellwright** (father)");
            sb.AppendLine("   - Same depth as Cass");
            sb.AppendLine("   - His relationship to the sealed journals, the shaking hands");
            sb.AppendLine("   - What he knows and what he's hiding");
            sb.AppendLine();
            sb.AppendLine("3. **Perin Bellwright** (brother)");
            sb.AppendLine("   - Even though he's absent for much of the story, he needs full depth");
            sb.AppendLine("   - What actually happened with the Corda contract");
            sb.AppendLine("   - His presence through absence");
            sb.AppendLine();
            sb.AppendLine("4. **Maret Corda** (antagonist)");
            sb.AppendLine("   - Not a villain -- someone whose interests conflicts with Cass's");
            sb.AppendLine("   - Her own wound/want/need/lie (she should be understandable)");
            sb.AppendLine();
            sb.AppendLine("5. **Rector Suvaine** (Academy Chancellor)");
            sb.AppendLine("   - The institutional antagonist -- the system personified");
            sb.AppendLine("   - She believes she's protecting Cantamura");
            sb.AppendLine();
            sb.AppendLine("6. **Torvald Hess** (Compact leader)");
            sb.AppendLine("   - The outsider perspective on the system");
            sb.AppendLine("   - What he represents thematically");
            sb.AppendLine();
            sb.AppendLine("7. **At least 1-2 additional characters** that the story needs");
            sb.AppendLine("   - A peer/friend for Cass at the Academy?");
            sb.AppendLine("   - Someone at the House of Corda who knows Perin?");
            sb.AppendLine("   - A Court Singer with divided loyalties?");
            sb.AppendLine();
            sb.AppendLine("FOR EACH CHARACTER INCLUDE:");
            sb.AppendLine("- Name, age, role");
            sb.AppendLine("- Ghost/Wound/Want/Need/Lie chain (for major characters)");
            sb.AppendLine("- Three sliders (proactivity/likability/competence) with numbers and justification");
            sb.AppendLine("- Arc type and arc trajectory");
            sb.AppendLine("- Speech pattern (all 8 dimensions, with example lines)");
            sb.AppendLine("- Physical appearance (specific, not generic)");
            sb.AppendLine("- Physical habits and unconscious tells");
            sb.AppendLine("- Secrets (what the reader doesn't learn immediately)");
            sb.AppendLine("- Key relationships (mapped to other characters)");
            sb.AppendLine("- Thematic role (what question does this character embody?)");
            sb.AppendLine();
            sb.AppendLine("IMPORTANT:");
            sb.AppendLine("- Characters must INTERCONNECT. Their wants should conflict with each other.");
            sb.AppendLine("- Every secret should be something that would CHANGE the story if revealed.");
            sb.AppendLine("- Speech patterns must be distinct enough to pass the no-tags test.");
            sb.AppendLine("- Give Cass habits that come from his gift (the pain, the constant listening).");
            sb.AppendLine("- The father's shaking hands should connect to something specific.");
            sb.AppendLine("- Maret Corda should be as fully realized as Cass -- a worthy antagonist.");
            sb.AppendLine("- Target ~3000-4000 words. Dense character work, not padding.");
            return sb.ToString();
        }

        public static string BuildOutlinePrompt(string seed, string mystery, string world, string characters, string voicePart2, string craft)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Build a complete chapter outline for this fantasy novel. Target: 22-26 chapters, ~80,000 words total (~3,000-4,000 words per chapter).");
            sb.AppendLine();
            sb.AppendLine("SEED CONCEPT:");
            sb.AppendLine(seed);
            sb.AppendLine();
            sb.AppendLine("THE CENTRAL MYSTERY (author's eyes only -- reader discovers gradually):");
            sb.AppendLine(mystery);
            sb.AppendLine();
            sb.AppendLine("WORLD BIBLE:");
            sb.AppendLine(world);
            sb.AppendLine();
            sb.AppendLine("CHARACTER REGISTRY:");
            sb.AppendLine(characters);
            sb.AppendLine();
            sb.AppendLine("VOICE (tone and register):");
            sb.AppendLine(voicePart2);
            sb.AppendLine();
            sb.AppendLine("CRAFT REFERENCE (structures to follow):");
            sb.AppendLine(craft);
            sb.AppendLine();
            sb.AppendLine("BUILD THE OUTLINE WITH:");
            sb.AppendLine();
            sb.AppendLine("## Act Structure");
            sb.AppendLine("Map out Act I (0-23%), Act II Part 1 (23-50%), Act II Part 2 (50-77%), Act III (77-100%).");
            sb.AppendLine("State the percentage marks for the key novel.");
            sb.AppendLine();
            sb.AppendLine("## Chapter-by-Chapter Outline");
            sb.AppendLine();
            sb.AppendLine("For EACH chapter, provide:");
            sb.AppendLine("### Ch N: [Title]");
            sb.AppendLine("- **POV:** (always Cass, third-person limited)");
            sb.AppendLine("- **Location:** Which districts/locations");
            sb.AppendLine("- **Save the Cat beat:** Which beat this chapter serves (Opening Image, Setup, Catalyst, etc.)");
            sb.AppendLine("- **% mark:** Where this falls in the novel");
            sb.AppendLine("- **Emotional arc:** Starting emotion → ending emotion");
            sb.AppendLine("- **Try-fail cycle:** Yes-but / No-and / No-but / Yes-and");
            sb.AppendLine("- **Beats:** 3-5 specific scene beats that must happen");
            sb.AppendLine("- **Plants:** Foreshadowing elements planted in this chapter");
            sb.AppendLine("- **Payoffs:** Foreshadowing elements that pay off here");
            sb.AppendLine("- **Character movement:** What changes for Cass (or other characters) by chapter's end");
            sb.AppendLine("- **The lie:** How Cass's lie (\"if I master the system, I can fix things from inside\") is reinforced or challenged in this chapter");
            sb.AppendLine("- **~Word count target:** for pacing");
            sb.AppendLine();
            sb.AppendLine("## Foreshadowing Ledger");
            sb.AppendLine();
            sb.AppendLine("A table tracking every planted thread:");
            sb.AppendLine("| Thread | Planted (Ch) | Reinforced (Ch) | Payoff (Ch) | Type |");
            sb.AppendLine();
            sb.AppendLine("Include at LEAST 15 threads. Types: object, dialogue, action, symbolic, structural.");
            sb.AppendLine();
            sb.AppendLine("KEY PLOT ARCHITECTURE:");
            sb.AppendLine();
            sb.AppendLine("Act I (Ch 1-6ish): Establish Cass's world, his pain, his gift, the Academy, his family.");
            sb.AppendLine("Plant the mystery early (the locked room, the forbidden bells, father's tremor).");
            sb.AppendLine("Catalyst: something forces Cass to investigate Perin's contract.");
            sb.AppendLine();
            sb.AppendLine("Act II Part 1 (Ch 7-12ish): Investigation. Cass digs into the Corda contract, encounters");
            sb.AppendLine("Maret, allies with Torvald and Lenne, begins hearing the harmonic more clearly.");
            sb.AppendLine("Midpoint: Cass learns a partial truth that changes his approach (false victory or defeat).");
            sb.AppendLine();
            sb.AppendLine("Act II Part 2 (Ch 13-18ish): Pressure mounts. Maret moves against the Bellwrights.");
            sb.AppendLine("Father's secrets begin to surface. Cass's lie is increasingly unsustainable.");
            sb.AppendLine("All Is Lost: Cass confronts his father and learns the full truth.");
            sb.AppendLine();
            sb.AppendLine("Act III (Ch 19-24ish): Cass understands the question. Must choose how to answer.");
            sb.AppendLine("The climax plays out using the established intervals of Tonal Law.");
            sb.AppendLine("The resolution shows the aftermath of his choice.");
            sb.AppendLine();
            sb.AppendLine("CONSTRAINTS:");
            sb.AppendLine("- The climax must be mechanically resolvable using established Tonal Law intervals");
            sb.AppendLine("- Cass's investigation should feel like a mystery plot overlaid on a coming-of-age arc");
            sb.AppendLine("- The Stability Trap: bad things must stay bad. Not everything resolves cleanly.");
            sb.AppendLine("- Perin must appear in person at some point (not just in memory/letters)");
            sb.AppendLine("- At least 3 chapters should be \"quiet\" -- character-focused, low-action, emotionally rich");
            sb.AppendLine("- Vary the try-fail types: 60%+ should be \"yes-but\" or \"no-and\"");
            sb.AppendLine("- The foreshadowing ledger must have plant-to-payoff distances of at least 3 chapters");
            return sb.ToString();
        }
    }
}
