using System;
using System.Text;

namespace Autonovel.Core.Prompts
{
    public static class EvaluationPrompts
    {
        public const string JudgeSystemPrompt = "You are a literary critic and novel editor. You evaluate fiction with precision. Always respond with valid JSON. No markdown fences, no preamble -- just the JSON object.";

        public static string BuildFoundationEvaluationPrompt(string voice, string world, string characters, string outline, string canon)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Evaluate these fantasy novel planning documents.");
            sb.AppendLine();
            sb.AppendLine("SCORING CALIBRATION (read this before scoring anything):");
            sb.AppendLine("  9-10: Could not improve this with a month of focused editorial work.");
            sb.AppendLine("        Published-novel quality. You can name the specific published");
            sb.AppendLine("        novel it competes with. Reserve 10 for work that SURPRISES you.");
            sb.AppendLine("  7-8:  Strong. A skilled author could draft from this document with");
            sb.AppendLine("        minimal invention. Gaps exist but are minor and enumerable.");
            sb.AppendLine("  5-6:  Functional but thin. A writer would need to invent significant");
            sb.AppendLine("        material on the fly. Major gaps or generic choices.");
            sb.AppendLine("  3-4:  Sketchy. More questions than answers. Would require heavy");
            sb.AppendLine("        supplementation before drafting.");
            sb.AppendLine("  1-2:  Placeholder or stub. Not usable for drafting.");
            sb.AppendLine("  0:    Empty or missing.");
            sb.AppendLine();
            sb.AppendLine("  A score of 8+ requires ZERO major gaps. A score of 9+ requires");
            sb.AppendLine("  that you genuinely struggled to find flaws. Err toward lower scores.");
            sb.AppendLine();
            sb.AppendLine("MANDATORY: For EVERY dimension, before scoring, you must identify:");
            sb.AppendLine("  (a) The single biggest GAP or WEAKNESS in that area");
            sb.AppendLine("  (b) A specific, actionable improvement that would raise the score");
            sb.AppendLine("  If you cannot find a gap, explain why you believe one doesn't exist.");
            sb.AppendLine();
            sb.AppendLine("VOICE DEFINITION:");
            sb.AppendLine(voice);
            sb.AppendLine();
            sb.AppendLine("WORLD BIBLE:");
            sb.AppendLine(world);
            sb.AppendLine();
            sb.AppendLine("CHARACTER REGISTRY:");
            sb.AppendLine(characters);
            sb.AppendLine();
            sb.AppendLine("OUTLINE:");
            sb.AppendLine(outline);
            sb.AppendLine();
            sb.AppendLine("CANON (established facts):");
            sb.AppendLine(canon);
            sb.AppendLine();
            sb.AppendLine("CROSS-CHECKS (perform these before scoring):");
            sb.AppendLine("1. Check all example dialogue lines against ANTI-SLOP patterns:");
            sb.AppendLine("   - Look for structural formulas repeated across characters");
            sb.AppendLine("     (\"not X, but Y\" / \"either X, or Y\" / \"there's a difference\")");
            sb.AppendLine("   - Check for AI rhetorical tics disguised as character voice");
            sb.AppendLine("   - Deduct from character_distinctiveness if multiple characters");
            sb.AppendLine("     share the same sentence structures");
            sb.AppendLine("2. Check for missing NEGATIVE SPACE -- what's absent?");
            sb.AppendLine("   - Are there gaps in the magic system that would block a specific");
            sb.AppendLine("     plot scene? (e.g., can Cass hear lies in written documents?");
            sb.AppendLine("     What happens during the climax -- what rule resolves it?)");
            sb.AppendLine("   - Are there characters needed for the plot who don't exist?");
            sb.AppendLine("   - Are there scenes the outline demands that the world can't support?");
            sb.AppendLine("3. Check for CONVENIENT GAPS vs DELIBERATE MYSTERY:");
            sb.AppendLine("   - Convenient: \"the details are unclear\" where specifics are needed");
            sb.AppendLine("   - Deliberate: withholding information from the READER while the");
            sb.AppendLine("     AUTHOR knows the answer. If the planning docs dodge a question");
            sb.AppendLine("     that a writer would need answered to draft a scene, that's a gap,");
            sb.AppendLine("     not an iceberg.");
            sb.AppendLine("4. Check the canon for INTERNAL CONTRADICTIONS:");
            sb.AppendLine("   - Cross-reference dates, ages, and timelines");
            sb.AppendLine("   - Check if character abilities match magic system rules");
            sb.AppendLine("   - Look for factual conflicts between documents");
            sb.AppendLine();
            sb.AppendLine("Score these dimensions (gap + improvement required for each):");
            sb.AppendLine();
            sb.AppendLine("LORE & WORLDBUILDING:");
            sb.AppendLine("- magic_system: Hard rules with COSTS and LIMITATIONS per Sanderson's");
            sb.AppendLine("  Second Law. Could a writer resolve the CLIMACTIC CONFLICT using only");
            sb.AppendLine("  rules already established? Are costs plot-driving, not decorative?");
            sb.AppendLine("  Are there at least 3 societal implications explored with specificity?");
            sb.AppendLine("  Is the system TESTABLE -- could you write a courtroom scene, a");
            sb.AppendLine("  contract negotiation, and a magical confrontation without inventing");
            sb.AppendLine("  new rules?");
            sb.AppendLine("- world_history: Timeline of events creating PRESENT-DAY tensions.");
            sb.AppendLine("  Each historical event should map to a current faction conflict or");
            sb.AppendLine("  character motivation. Decorative history (cool but plot-irrelevant)");
            sb.AppendLine("  counts against the score, not for it.");
            sb.AppendLine("- geography_and_culture: Locations distinct with sensory signatures.");
            sb.AppendLine("  Cultures with specific customs that GENERATE CONFLICT. Economy that");
            sb.AppendLine("  creates class tension. Check: could two different scenes set in two");
            sb.AppendLine("  different locations feel meaningfully different based on what's here?");
            sb.AppendLine("- lore_interconnection: Does changing one element force changes in");
            sb.AppendLine("  at least two others? Test by mentally removing the magic system --");
            sb.AppendLine("  does the political structure collapse? Does the class system change?");
            sb.AppendLine("  If elements are modular/detachable, score low.");
            sb.AppendLine("- iceberg_depth: Implied depth vs stated depth. But CHECK: does the");
            sb.AppendLine("  author actually know the answers to the mysteries, or are they");
            sb.AppendLine("  handwaving? If a planning doc says \"the answer will be revealed\"");
            sb.AppendLine("  without specifying WHAT the answer is, that's a gap wearing an");
            sb.AppendLine("  iceberg costume.");
            sb.AppendLine();
            sb.AppendLine("CHARACTER:");
            sb.AppendLine("- character_depth: Wound/want/need/lie chains that are CAUSALLY LINKED");
            sb.AppendLine("  (not just thematically associated). The lie must logically follow");
            sb.AppendLine("  from the wound. The want must be the wrong solution to the lie.");
            sb.AppendLine("  The need must directly oppose the want. Check each chain for");
            sb.AppendLine("  logical gaps. Also check: are ANY characters missing wound/want/need");
            sb.AppendLine("  chains who probably need them?");
            sb.AppendLine("- character_distinctiveness: Remove all dialogue tags from the example");
            sb.AppendLine("  lines. Can you identify the speaker from sentence structure alone?");
            sb.AppendLine("  Check for REPEATED STRUCTURAL FORMULAS across characters (e.g.,");
            sb.AppendLine("  multiple characters using \"X. Not Y.\" or balanced antithesis).");
            sb.AppendLine("  Check that metaphor domains don't overlap. Check that speech");
            sb.AppendLine("  patterns reflect character background (a 14-year-old should not");
            sb.AppendLine("  sound like a 60-year-old merchant).");
            sb.AppendLine("- character_secrets: Each major character's secret should be something");
            sb.AppendLine("  that, if revealed, changes the plot's trajectory. Vague secrets");
            sb.AppendLine("  (\"he knows more than he says\") score lower than specific ones");
            sb.AppendLine("  (\"he knows the harmonic means X, which would invalidate Y\").");
            sb.AppendLine();
            sb.AppendLine("STRUCTURE:");
            sb.AppendLine("- outline_completeness: Chapters with beats, POV, emotional arc,");
            sb.AppendLine("  try-fail cycle type. Save the Cat beats at correct % marks.");
            sb.AppendLine("  Score 0 if empty. Score 5+ only if act structure exists.");
            sb.AppendLine("- foreshadowing_balance: Every planted thread has a planned payoff.");
            sb.AppendLine("  Score 0 if ledger is empty regardless of implicit threads in");
            sb.AppendLine("  other documents -- foreshadowing must be TRACKED to count.");
            sb.AppendLine();
            sb.AppendLine("CRAFT:");
            sb.AppendLine("- internal_consistency: Actively hunt for contradictions. Cross-ref");
            sb.AppendLine("  dates, ages, character counts, named locations. Flag any case");
            sb.AppendLine("  where documents disagree. A single major contradiction caps this");
            sb.AppendLine("  at 6. Three or more caps at 4.");
            sb.AppendLine("- voice_clarity: Voice definition must be specific and ACTIONABLE.");
            sb.AppendLine("  Exemplar passages must demonstrate the voice. Anti-exemplars must");
            sb.AppendLine("  define boundaries. Check exemplar dialogue for AI slop patterns.");
            sb.AppendLine("  A voice doc that is beautiful but contains slop in its own examples");
            sb.AppendLine("  is undermined -- deduct.");
            sb.AppendLine("- canon_coverage: Facts logged, sourced, and sufficient to catch");
            sb.AppendLine("  contradictions. Check: if a writer introduced a NEW fact in");
            sb.AppendLine("  chapter 5, could they verify it against the canon? Is the canon");
            sb.AppendLine("  granular enough? Are there known facts from other docs that");
            sb.AppendLine("  AREN'T in the canon?");
            sb.AppendLine();
            sb.AppendLine("Respond with JSON:");
            sb.AppendLine("{");
            sb.AppendLine("  \"magic_system\": {\"score\": N, \"gap\": \"biggest weakness\", \"fix\": \"specific improvement\", \"note\": \"...\"},");
            sb.AppendLine("  \"world_history\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"geography_and_culture\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"lore_interconnection\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"iceberg_depth\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"character_depth\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"character_distinctiveness\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"character_secrets\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"outline_completeness\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"foreshadowing_balance\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"internal_consistency\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"voice_clarity\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"canon_coverage\": {\"score\": N, \"gap\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"slop_in_planning_docs\": {\"found\": [\"list any AI slop patterns found in exemplar dialogue, voice examples, or character descriptions\"], \"note\": \"...\"},");
            sb.AppendLine("  \"contradictions_found\": [\"list any factual contradictions between documents\"],");
            sb.AppendLine("  \"overall_score\": N,");
            sb.AppendLine("  \"lore_score\": N,");
            sb.AppendLine("  \"weakest_dimension\": \"...\",");
            sb.AppendLine("  \"top_3_improvements\": [\"ranked list of the 3 highest-leverage improvements\"]");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("WEIGHTING: lore/worldbuilding 40%, character 30%, structure 20%, craft 10%.");
            sb.AppendLine("A novel with thin worldbuilding but a complete outline is WORSE than deep");
            sb.AppendLine("worldbuilding with an incomplete outline.");
            sb.AppendLine();
            sb.AppendLine("FINAL CHECK: If your overall_score is above 7, re-read your gap lists.");
            sb.AppendLine("If any gap describes a problem that would force a writer to stop and");
            sb.AppendLine("invent something during drafting, your score is too high. Revise down.");
            return sb.ToString();
        }

        public static string BuildChapterEvaluationPrompt(string voice, string world, string characters, string canon, string chapterOutline, string prevChapterTail, string chapterText)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Evaluate this fantasy novel chapter against the planning docs.");
            sb.AppendLine();
            sb.AppendLine("SCORING CALIBRATION:");
            sb.AppendLine("  9-10: Among the best chapters you've read in published fantasy. Name");
            sb.AppendLine("        a specific published chapter it competes with, or don't give 9+.");
            sb.AppendLine("  7-8:  Strong, publishable with editorial polish. Specific flaws exist");
            sb.AppendLine("        but don't break the reading experience.");
            sb.AppendLine("  5-6:  Functional but flat. A competent draft that needs substantial revision.");
            sb.AppendLine("        Generic where it should be specific. Safe where it should risk.");
            sb.AppendLine("  3-4:  Significant problems. Voice breaks, beats missed, prose generic.");
            sb.AppendLine("  1-2:  Not usable. Rewrite from scratch.");
            sb.AppendLine();
            sb.AppendLine("  The MEDIAN score for a competent AI-generated chapter should be 6.");
            sb.AppendLine("  A 7 means it does something a generic AI draft wouldn't.");
            sb.AppendLine("  An 8 means a human editor would keep it with minor notes.");
            sb.AppendLine("  Most dimensions should score 6-7. Reserve 8+ for genuine excellence.");
            sb.AppendLine();
            sb.AppendLine("MANDATORY: For each dimension, you must identify:");
            sb.AppendLine("  (a) The single WEAKEST MOMENT -- quote the specific sentence or passage");
            sb.AppendLine("  (b) What would make it better -- a concrete revision, not a vague note");
            sb.AppendLine("  If every sentence is perfect, you're not reading carefully enough.");
            sb.AppendLine();
            sb.AppendLine("VOICE DEFINITION:");
            sb.AppendLine(voice);
            sb.AppendLine();
            sb.AppendLine("WORLD BIBLE (summary):");
            sb.AppendLine(world);
            sb.AppendLine();
            sb.AppendLine("CHARACTER REGISTRY:");
            sb.AppendLine(characters);
            sb.AppendLine();
            sb.AppendLine("CANON (established hard facts -- violations are bugs):");
            sb.AppendLine(canon);
            sb.AppendLine();
            sb.AppendLine("CHAPTER OUTLINE ENTRY:");
            sb.AppendLine(chapterOutline);
            sb.AppendLine();
            sb.AppendLine("PREVIOUS CHAPTER (last 1500 words):");
            sb.AppendLine(prevChapterTail);
            sb.AppendLine();
            sb.AppendLine("THE CHAPTER TO EVALUATE:");
            sb.AppendLine(chapterText);
            sb.AppendLine();
            sb.AppendLine("CROSS-CHECKS (perform before scoring):");
            sb.AppendLine("1. QUOTE TEST: Find the 3 best sentences and 3 weakest sentences.");
            sb.AppendLine("   If you can't find 3 weak ones, lower your standards -- every");
            sb.AppendLine("   chapter has weak moments. Look for: generic phrasing where");
            sb.AppendLine("   specificity was possible, rhythmic monotony in any paragraph,");
            sb.AppendLine("   metaphors that don't come from the character's experience,");
            sb.AppendLine("   emotional moments that tell instead of show, transitions that");
            sb.AppendLine("   summarize instead of dramatize.");
            sb.AppendLine("2. DIALOGUE REALISM: Read all dialogue aloud (mentally). Does it");
            sb.AppendLine("   sound like speech or like written prose? Do characters say things");
            sb.AppendLine("   a 14-year-old / 60-year-old / etc. would actually say?");
            sb.AppendLine("3. SCENE VS SUMMARY: How much of the chapter is in-scene (moment");
            sb.AppendLine("   by moment, with dialogue and action) vs summary (narrator");
            sb.AppendLine("   compressing time)? Chapters heavy on summary score lower on");
            sb.AppendLine("   engagement regardless of prose quality.");
            sb.AppendLine("4. AI PATTERN CHECK: Look for these common AI writing patterns:");
            sb.AppendLine("   - Every paragraph the same length");
            sb.AppendLine("   - Observations always in threes (X, Y, and Z)");
            sb.AppendLine("   - Emotional beats that arrive on schedule rather than surprising");
            sb.AppendLine("   - Characters who never say the wrong thing or talk past each other");
            sb.AppendLine("   - Description that catalogs instead of selecting (listing 5 sensory");
            sb.AppendLine("     details when 2 specific ones would be sharper)");
            sb.AppendLine("   - Internal monologue explaining what the scene already showed");
            sb.AppendLine("5. EARNED VS GIVEN: Is tension earned through scene work or handed to");
            sb.AppendLine("   the reader through the narrator's assertions? Is mystery maintained");
            sb.AppendLine("   through genuine withholding or through the character conveniently");
            sb.AppendLine("   not thinking about things they'd think about?");
            sb.AppendLine();
            sb.AppendLine("Score these dimensions:");
            sb.AppendLine();
            sb.AppendLine("- voice_adherence: Does the prose match voice.md Part 2? Check: sentence");
            sb.AppendLine("  rhythm variation, vocabulary wells, body-before-emotion principle,");
            sb.AppendLine("  the specific tone described. Quote the strongest voice moment AND");
            sb.AppendLine("  the weakest. Does ANY passage sound like generic fantasy prose that");
            sb.AppendLine("  could appear in any novel? If yes, score 7 max.");
            sb.AppendLine();
            sb.AppendLine("- beat_coverage: Did it hit every beat from the outline? Were beats");
            sb.AppendLine("  dramatized or merely mentioned? A beat that's summarized in a sentence");
            sb.AppendLine("  instead of lived in a scene counts as half-hit. Score reflects");
            sb.AppendLine("  QUALITY of beat execution, not just presence.");
            sb.AppendLine();
            sb.AppendLine("- character_voice: Remove all dialogue tags mentally. Can you tell who's");
            sb.AppendLine("  speaking? Do characters ever sound alike? Does dialogue read as speech");
            sb.AppendLine("  or as written prose? Does Cass sound like a specific 14-year-old, or");
            sb.AppendLine("  like \"young protagonist\"? Does anyone say something surprising -- not");
            sb.AppendLine("  just the right thing, but a REAL thing? Characters who never stumble,");
            sb.AppendLine("  hesitate, or say something slightly wrong are AI-pattern characters.");
            sb.AppendLine();
            sb.AppendLine("- plants_seeded: Were foreshadowing elements placed naturally? A plant");
            sb.AppendLine("  that's obvious is worse than a plant that's invisible. Score based on");
            sb.AppendLine("  HOW WELL they're integrated, not just whether they're present.");
            sb.AppendLine();
            sb.AppendLine("- prose_quality: Sentence variety (measure: do 3+ consecutive sentences");
            sb.AppendLine("  start the same way?). Specificity (concrete nouns > abstract).");
            sb.AppendLine("  Metaphors from Cass's experience, not from a thesaurus. Show-don't-tell");
            sb.AppendLine("  at emotional peaks. QUOTE the weakest sentence and explain why. Also");
            sb.AppendLine("  check for: repeated phrases, leaned-on constructions, paragraphs that");
            sb.AppendLine("  could be cut without loss.");
            sb.AppendLine();
            sb.AppendLine("- continuity: Does it follow logically from the previous chapter? Emotional");
            sb.AppendLine("  continuity as well as plot continuity. Does the character's state of");
            sb.AppendLine("  mind track?");
            sb.AppendLine();
            sb.AppendLine("- canon_compliance: Check ALL facts against canon. List violations.");
            sb.AppendLine("  One major violation caps score at 6. Check: character names, locations,");
            sb.AppendLine("  magic system rules, timeline, established events, physical descriptions.");
            sb.AppendLine();
            sb.AppendLine("- lore_integration: Does the world do WORK in this chapter, or is it");
            sb.AppendLine("  set dressing? A scene that could happen in any fantasy city with");
            sb.AppendLine("  find-and-replace on proper nouns scores 5 max.");
            sb.AppendLine();
            sb.AppendLine("- engagement: Would a reader turn the page? Where does tension come from --");
            sb.AppendLine("  plot, character, mystery, prose? Is there a moment that SURPRISES?");
            sb.AppendLine("  Predictable excellence is still predictable. Score 8+ only if the");
            sb.AppendLine("  chapter does something unexpected.");
            sb.AppendLine();
            sb.AppendLine("Respond with JSON:");
            sb.AppendLine("{");
            sb.AppendLine("  \"voice_adherence\": {\"score\": N, \"weakest_moment\": \"quote the specific weak passage\", \"fix\": \"how to improve it\", \"note\": \"...\"},");
            sb.AppendLine("  \"beat_coverage\": {\"score\": N, \"weakest_moment\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"character_voice\": {\"score\": N, \"weakest_moment\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"plants_seeded\": {\"score\": N, \"weakest_moment\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"prose_quality\": {\"score\": N, \"weakest_sentence\": \"quote it\", \"fix\": \"rewrite suggestion\", \"strongest_sentence\": \"quote it\", \"note\": \"...\"},");
            sb.AppendLine("  \"continuity\": {\"score\": N, \"note\": \"...\"},");
            sb.AppendLine("  \"canon_compliance\": {\"score\": N, \"violations\": [\"list any found\"], \"note\": \"...\"},");
            sb.AppendLine("  \"lore_integration\": {\"score\": N, \"weakest_moment\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"engagement\": {\"score\": N, \"weakest_moment\": \"...\", \"fix\": \"...\", \"note\": \"...\"},");
            sb.AppendLine("  \"three_weakest_sentences\": [\"quote 1\", \"quote 2\", \"quote 3\"],");
            sb.AppendLine("  \"three_strongest_sentences\": [\"quote 1\", \"quote 2\", \"quote 3\"],");
            sb.AppendLine("  \"ai_patterns_detected\": [\"list any AI writing patterns found\"],");
            sb.AppendLine("  \"overall_score\": N,");
            sb.AppendLine("  \"weakest_dimension\": \"...\",");
            sb.AppendLine("  \"top_3_revisions\": [\"specific, actionable revision 1\", \"revision 2\", \"revision 3\"],");
            sb.AppendLine("  \"new_canon_entries\": [\"any new facts established in this chapter\"]");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("FINAL CHECK: If your overall_score is above 7, re-read your weakest_moment");
            sb.AppendLine("quotes. If any of them describe a problem that an editor would flag, your");
            sb.AppendLine("score is too high. The median AI chapter is a 6. An 8 is exceptional. A 9");
            sb.AppendLine("is rare. A 10 does not exist for a first draft.");
            return sb.ToString();
        }

        public const string AdversarialEditSystemPrompt = "You are a ruthless literary editor. You cut fat from prose. You have no sentiment about good-enough sentences -- if a sentence isn't earning its place, it goes. You quote exactly from the text. You never invent or paraphrase. Always respond with valid JSON.";

        public static string BuildAdversarialEditPrompt(string chapterText, int wordCount)
        {
            var sb = new StringBuilder();
            sb.AppendLine("You are editing a fantasy novel chapter. Your job: identify exactly");
            sb.AppendLine("what to cut or rewrite to make this chapter tighter, sharper, more alive.");
            sb.AppendLine();
            sb.AppendLine($"THE CHAPTER ({wordCount} words):");
            sb.AppendLine(chapterText);
            sb.AppendLine();
            sb.AppendLine("YOUR TASK:");
            sb.AppendLine("1. Find 10-20 specific passages that should be CUT or REWRITTEN.");
            sb.AppendLine("   For each, quote the EXACT text (minimum 10 words of the quote so");
            sb.AppendLine("   it's unambiguous), explain why it's weak, and classify it.");
            sb.AppendLine();
            sb.AppendLine("2. Classify each cut as one of:");
            sb.AppendLine("   - FAT: adds nothing, could be removed with no loss");
            sb.AppendLine("   - REDUNDANT: restates what a previous sentence/scene already showed");
            sb.AppendLine("   - OVER-EXPLAIN: narrator explaining what the scene already demonstrated");
            sb.AppendLine("   - GENERIC: could appear in any novel, not specific to this world/character");
            sb.AppendLine("   - TELL: names an emotion or state instead of showing it");
            sb.AppendLine("   - STRUCTURAL: paragraph/section that disrupts pacing or rhythm");
            sb.AppendLine();
            sb.AppendLine("3. For REWRITE candidates (not cuts), provide a specific revision.");
            sb.AppendLine();
            sb.AppendLine("4. Estimate how many words could be cut total without losing anything");
            sb.AppendLine("   the chapter needs.");
            sb.AppendLine();
            sb.AppendLine("Respond with JSON:");
            sb.AppendLine("{");
            sb.AppendLine("  \"cuts\": [");
            sb.AppendLine("    {");
            sb.AppendLine("      \"quote\": \"exact text from the chapter (10+ words)\",");
            sb.AppendLine("      \"type\": \"FAT|REDUNDANT|OVER-EXPLAIN|GENERIC|TELL|STRUCTURAL\",");
            sb.AppendLine("      \"reason\": \"why this should go\",");
            sb.AppendLine("      \"action\": \"CUT or REWRITE\",");
            sb.AppendLine("      \"rewrite\": \"replacement text if action is REWRITE, null if CUT\"");
            sb.AppendLine("    }");
            sb.AppendLine("  ],");
            sb.AppendLine("  \"total_cuttable_words\": N,");
            sb.AppendLine("  \"tightest_passage\": \"quote the best 2-3 sentences in the chapter -- the ones you'd never touch\",");
            sb.AppendLine("  \"loosest_passage\": \"quote the worst 2-3 sentences -- the ones that most need work\",");
            sb.AppendLine("  \"overall_fat_percentage\": N,");
            sb.AppendLine("  \"one_sentence_verdict\": \"what this chapter does well and what drags it down, in one sentence\"");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static Dictionary<string, (string Name, string System)> GetReaders() => new()
        {
            { "editor", ("The Editor", "You are a senior fiction editor at a major publishing house. You've edited 200+ novels. You care about prose texture, subtext, sentence-level craft, and whether the voice is consistent and earned. You notice when the narrator over-explains, when dialogue sounds written rather than spoken, when a metaphor is borrowed rather than earned. You are not cruel but you are precise. You've seen enough competent prose to know the difference between good and alive. You respond with valid JSON only.") },
            { "genre_reader", ("The Genre Reader", "You are an avid fantasy reader who reads 50+ novels a year. You care about pacing, mystery, worldbuilding payoff, and whether you want to keep turning pages. You get bored by beautiful prose that doesn't GO anywhere. You notice when an investigation stalls, when tension plateaus, when the author is more in love with their world than their story. You compare everything to Sanderson, Le Guin, Jemisin, Rothfuss, Hobb. You are generous with what you love and blunt about what bores you. You respond with valid JSON only.") },
            { "writer", ("The Writer", "You are a published fantasy author with 5 novels and a Hugo nomination. You read as a craftsperson. You notice structure: where the beats fall, whether foreshadowing pays off, whether character arcs complete. You notice when technique shows versus when it disappears into the story. The highest compliment you give is 'I forgot I was reading.' The worst thing you can say is 'I can see the outline.' You care about the gap between what a novel attempts and what it achieves. You respond with valid JSON only.") },
            { "first_reader", ("The First Reader", "You are a thoughtful general reader. Not a writer, not an editor, not a genre expert. You read for the experience. You know what you feel but not always why. You notice when you're moved, when you're bored, when you're confused, when you want to tell someone about what you just read. You don't use craft terminology. You say things like 'I didn't care about this part' and 'I had to put the book down after this scene because I needed a minute.' Your feedback is emotional and honest, not analytical. You respond with valid JSON only.") }
        };

        public static string BuildReaderPanelPrompt(string arcSummary)
        {
            var sb = new StringBuilder();
            sb.AppendLine("You have just read a complete fantasy novel in summary form.");
            sb.AppendLine("The summaries include chapter-by-chapter events, opening and closing passages");
            sb.AppendLine("from each chapter, and key dialogue. The full novel is 72,422 words across");
            sb.AppendLine("24 chapters.");
            sb.AppendLine();
            sb.AppendLine(arcSummary);
            sb.AppendLine();
            sb.AppendLine("Now answer these questions about the NOVEL AS A WHOLE. Be specific.");
            sb.AppendLine("Quote passages when you can. Name chapter numbers.");
            sb.AppendLine();
            sb.AppendLine("Respond with JSON:");
            sb.AppendLine("{");
            sb.AppendLine("  \"momentum_loss\": \"Where does the story lose momentum? Name the specific chapter(s) and what causes the drag. If it never loses momentum, say so and explain why.\",");
            sb.AppendLine("  \"earned_ending\": \"Does the ending feel earned by everything before it? Does Cass's choice in Ch 22 land? Does the final image in Ch 24 mirror Ch 1 in a way that satisfies? What, if anything, feels unearned?\",");
            sb.AppendLine("  \"cut_candidate\": \"If the novel had to be 10% shorter (~7,000 words), which chapter or section would you cut first? Why? What would be lost?\",");
            sb.AppendLine("  \"missing_scene\": \"Is there a scene the novel NEEDS that it doesn't have? A conversation that should happen, a moment that's earned but never delivered, a character who deserves more page time? Be specific about where it would go.\",");
            sb.AppendLine("  \"thinnest_character\": \"Which character feels thinnest by the end? Who do you want to know more about? Who could be cut without the novel suffering?\",");
            sb.AppendLine("  \"best_scene\": \"What's the single best scene in the novel? Quote the moment that made you feel something. Why does it work?\",");
            sb.AppendLine("  \"worst_scene\": \"What's the single weakest scene? What goes wrong? How would you fix it?\",");
            sb.AppendLine("  \"would_recommend\": \"Would you recommend this novel? To whom? What would you say about it in one sentence?\",");
            sb.AppendLine("  \"haunts_you\": \"Is there a line or moment that stays with you after reading? Quote it.\",");
            sb.AppendLine("  \"next_book\": \"Would you read the author's next book? Why or why not?\"");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
